on:
  push:
    branches:
      - 'nonprd'
    paths:
      - "overlay/**/service-conf/*.json"
      - "**/*.j2"
      - "**/generate-gw-resources.sh"
  workflow_dispatch:
jobs:
  GenerateGatewayResources:
    runs-on: [self-hosted, b2p]
    steps:
      - name: SetupPython
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      
      - name: PipInstall
        run: |
          pip install Jinja2
          pip install jinja2-cli

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'

      - name: GenerateGatewayResources
        run: |
          ./generate-gw-resources.sh

      - name: UpdateRepo
        run: |
          git add -A
          git diff --cached --exit-code --quiet && exit 0 || echo "Detected Changes"
          git commit -a -m "Update kubernetes yaml file."
          git pull
          git push
