on:
  push:
    branches:
      - 'nonprd'
    paths:
      - "overlay/hotfix/az-app-gw/path-ms-api.conf"
      - "az-app-gw/path-*.conf"
      - "update-az-app-gw-path-map.sh"
  workflow_dispatch:
jobs:
  GenerateGatewayResources:
    runs-on: [self-hosted, b2p]
    steps:
      - name: SetupPython
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      
      - name: PipInstall
        run: |
          pip install Jinja2
          pip install jinja2-cli

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'

      - name: AzureLogin (NONPRD)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.PAYZAVE_AZURE_CLIENT_ID }} -p ${{ secrets.PAYZAVE_AZURE_CREDENTIALS }} --tenant ${{ secrets.PAYZAVE_AZURE_TENANT_ID }} --output none
            az account set -s ${{ secrets.PAYZAVE_AZURE_SUBSCRIPTION_ID_NONPRD }}

      - name: GenerateGatewayResources
        run: |
          - ./update-az-app-gw-path-map.sh hotfix ${{ secrets.PAYZAVE_AZURE_CLIENT_ID }} ${{ secrets.PAYZAVE_AZURE_CREDENTIALS }} ${{ secrets.PAYZAVE_AZURE_TENANT_ID }}
