name: Backend Test
on:
  workflow_call:
jobs:
  Test:
    # runs-on: ubuntu-latest
    # container: openjdk:17-jdk-alpine3.14
    runs-on: [self-hosted, b2p]
    container: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine
    # container: openjdk:18-jdk-alpine3.15
    # container: openjdk:15-jdk-alpine3.12
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.PAYZAVE_GIT_USER }}
          git config --global user.email ${{ secrets.PAYZAVE_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.PAYZAVE_ACR_REGISTRY }}
          username: ${{ secrets.PAYZAVE_ACR_USER }}
          password: ${{ secrets.PAYZAVE_ACR_TOKEN }}

      - name: BuildTools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kustomize: '3.9.1' #'4.5.7'
          # skaffold: '1.17.2' #'1.39.1'
          skaffold: '1.39.1'
          helm: '3.9.4'
          kubectl: '1.17.8' #'1.20.2'
          yq: '4.7.1'

      - name: SetupGradle
        uses: gradle/gradle-build-action@v2
        with:
          # gradle-version: 7.2
          gradle-version: 6.7

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: SetupMaven
        run: |
          mkdir -p .gradle
          echo "mavenUsername=${{ secrets.PAYZAVE_NEXUS_USER }}" > .gradle/gradle.properties
          echo "mavenPassword=${{ secrets.PAYZAVE_NEXUS_PASSWORD }}" >> .gradle/gradle.properties

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

##### CodeScan
      - name: SonarQubeScan
        if: contains(github.ref_name, 'SONAR')
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.PAYZAVE_SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.PAYZAVE_SONARQUBE_HOST_URL }}
          LC_ALL: "en_US.UTF-8"
        with:
          projectBaseDir: src
          args: >
            -Dsonar.projectName=PAYZAVE-${{ secrets.PAYZAVE_SERVICENAME }}
            -Dsonar.projectKey=PAYZAVE-${{ secrets.PAYZAVE_SERVICENAME }}

##### Test
      - name: CleanTest
        if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/master'
        uses: gradle/gradle-build-action@v2
        env: 
          LD_LIBRARY_PATH: /usr/lib
        with:
          gradle-version: 7.2
          arguments: |
              clean test
