on:
  workflow_call:
jobs:
  FlywayRelease:
    # runs-on: ubuntu-latest
    # runs-on: [self-hosted, payzave]
    runs-on: [self-hosted, b2p]
    # container: openjdk:17-jdk-alpine3.14
    # container: gcr.io/k8s-skaffold/skaffold:v1.18.0
    container: adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine
    # container: openjdk:18-jdk-alpine3.15
    # container: openjdk:15-jdk-alpine3.12
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.PAYZAVE_GIT_USER }}
          git config --global user.email ${{ secrets.PAYZAVE_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: DockerLogin
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.PAYZAVE_ACR_REGISTRY }}
          username: ${{ secrets.PAYZAVE_ACR_USER }}
          password: ${{ secrets.PAYZAVE_ACR_TOKEN }}

      - name: BuildTools
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '3.9.1' #'4.5.7'
          # skaffold: '1.18.0' #'1.39.1'
          skaffold: '1.39.1'
          helm: '3.9.4'
          kubectl: '1.17.8' #'1.20.2'
          yq: '4.7.1'

      - name: SetupGradle
        uses: gradle/gradle-build-action@v2
        with:
          # gradle-version: 7.2
          gradle-version: 6.7

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: BuildFlywayContainerSnapshotImage
        if: contains( github.ref_name, 'dev' ) && github.event_name == 'push'
        run: |
          cd db
          echo -e "\e[92m START BuildFlywayContainerSnapshotImage \e[0m"
          skaffold build --cache-file .skaffold/cache -q > build.json
          echo -e "\e[92m FINISH BuildFlywayContainerSnapshotImage \e[0m"
          IMG_NAME=$(jq -r ".builds[0].imageName" build.json)
          IMG_WITH_TAG=$(jq -r ".builds[0].tag" build.json)
          IMG_VERSION=$(echo ${IMG_WITH_TAG}  | cut -d ":" -f 2 | cut -d "@" -f 1)
          SVC_NAME=$(echo ${IMG_NAME} | grep -o '[^/]*$')
          echo IMG_NAME="${IMG_NAME}" >> variables
          echo IMG_WITH_TAG="${IMG_WITH_TAG}" >> variables
          echo IMG_VERSION="${IMG_VERSION}" >> variables
          echo -e "\e[95m ${IMG_WITH_TAG}"
          echo SVC_NAME="$(echo "${{ secrets.PAYZAVE_SERVICENAME }}" | sed "s/-db-migration//")" >> variables

      - name: UpdateFlywayJobSnapshotTemplate 
        if: contains( github.ref_name, 'dev' ) && github.event_name == 'push'
        # if: github.event_name == 'push' && contains( github.ref, 'refs/tag' ) && contains(github.event.head_commit.message, 'hotfix')
        run: |
          echo -e "\e[92m START UpdateFlywayJobSnapshotTemplate \e[0m"
          source db/variables
          # git clone https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
          git clone https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
          cd payzave-app-deployment
          git checkout nonprd
          cd overlay/${{ github.ref_name }}
          kustomize edit set image ${IMG_NAME}=${IMG_NAME}:${IMG_VERSION}
          cd ../..
          git add -A
          git diff --cached --exit-code --quiet && NOCHG="0" || echo -e "\e[96m Detected Changes"
          if [[ "${NOCHG}" != "0" ]]; then
            git commit -a -m "Update deployment image [${IMG_WITH_TAG}]"
          fi
          ###### Handle Pull & Push Retry ######
          retry=0
          while [ "${retry}" -lt 3 ]
          do
            # git pull https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
            # git push https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
            git pull https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
            git push https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
            ppResult=$?
            echo -e "\e[31m P&P Result \e[0m : \e[96m $ppResult";
            if [[ "${ppResult}" == "" || "${ppResult}" -eq 0 || -z "${ppResult}" ]]; then
              echo -e "\e[92m Update Deployment success \e[0m"
              break
            else
              retry=$((retry+1))
              if [ "${retry}" -eq 3 ]; then
                echo -e "\e[31m Update Deployment failed, limit exceeded, MANUAL RETRY NEEDED \e[0m"
                exit 1
              else
                echo -e "\e[93m Update Deployment failed, retrying : \e[96m $retry \e[0m"
              fi
            fi
          done
          echo -e "\e[92m ${IMG_NAME}:${IMG_VERSION} \e[0m"
          echo -e "\e[92m FINISH UpdateFlywayJobSnapshotTemplate \e[0m"

      - name: BuildFlywayContainerReleaseImage
        if: github.ref_type == 'tag' && !(contains(github.event.head_commit.message, 'hotfix')) && github.event.head_commit.message != null && github.event.head_commit.message != ''
        # if: !(contains(github.ref_name, 'hotfix')) && github.event_name == 'push' && !(contains(github.event.head_commit.message, 'hotfix'))
        run: |
          cd db
          echo -e "\e[92m START BuildFlywayContainerReleaseImage \e[0m"
          skaffold build --cache-file .skaffold/cache -q --tag ${{ github.ref_name }}  > build.json
          echo -e "\e[92m FINISH BuildFlywayContainerReleaseImage \e[0m"
          IMG_NAME=$(jq -r ".builds[0].imageName" build.json)
          IMG_WITH_TAG=$(jq -r ".builds[0].tag" build.json)
          IMG_VERSION=$(echo ${IMG_WITH_TAG}  | cut -d ":" -f 2 | cut -d "@" -f 1)
          SVC_NAME=$(echo ${IMG_NAME} | grep -o '[^/]*$')
          echo IMG_NAME="${IMG_NAME}" >> variables
          echo IMG_WITH_TAG="${IMG_WITH_TAG}" >> variables
          echo IMG_VERSION="${IMG_VERSION}" >> variables
          echo -e "\e[95m ${IMG_WITH_TAG}"
          echo SVC_NAME="$(echo "${{ secrets.PAYZAVE_SERVICENAME }}" | sed "s/-db-migration//")" >> variables

      - name: UpdateFlywayJobReleaseTemplate 
        if: github.ref_type == 'tag' && !(contains(github.event.head_commit.message, 'hotfix')) && github.event.head_commit.message != null && github.event.head_commit.message != ''
        # if: github.event_name == 'push' && contains( github.ref, 'refs/tag' ) && contains(github.event.head_commit.message, 'hotfix')
        run: |
          echo -e "\e[92m START UpdateFlywayJobReleaseTemplate \e[0m"
          source db/variables
          # git clone https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
          git clone https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
          cd payzave-app-deployment
          git checkout nonprd
          cd overlay/sit
          kustomize edit set image ${IMG_NAME}=${IMG_NAME}:${IMG_VERSION}
          cd ../..
          git add -A
          git diff --cached --exit-code --quiet && NOCHG="0" || echo -e "\e[96m Detected Changes"
          if [[ "${NOCHG}" != "0" ]]; then
            git commit -a -m "Update deployment image [${IMG_WITH_TAG}]"
          fi
          ###### Handle Pull & Push Retry ######
          retry=0
          while [ "${retry}" -lt 3 ]
          do
            # git pull https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
            # git push https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
            git pull https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
            git push https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
            ppResult=$?
            echo -e "\e[31m P&P Result \e[0m : \e[96m $ppResult";
            if [[ "${ppResult}" == "" || "${ppResult}" -eq 0 || -z "${ppResult}" ]]; then
              echo -e "\e[92m Update Deployment success \e[0m"
              break
            else
              retry=$((retry+1))
              if [ "${retry}" -eq 3 ]; then
                echo -e "\e[31m Update Deployment failed, limit exceeded, MANUAL RETRY NEEDED \e[0m"
                exit 1
              else
                echo -e "\e[93m Update Deployment failed, retrying : \e[96m $retry \e[0m"
              fi
            fi
          done
          echo -e "\e[92m ${IMG_NAME}:${IMG_VERSION} \e[0m"
          echo -e "\e[92m FINISH UpdateFlywayJobReleaseTemplate \e[0m"

      - name: BuildFlywayContainerHotfixReleaseImage
        if: github.ref_type == 'tag' && contains(github.event.head_commit.message, 'hotfix') && github.event.head_commit.message != null && github.event.head_commit.message != ''
        run: |
          cd db
          echo -e "\e[92m START BuildFlywayContainerHotfixReleaseImage \e[0m"
          skaffold build --cache-file .skaffold/cache -q --tag ${{ github.ref_name }} > build.json
          echo -e "\e[92m FINISH BuildFlywayContainerHotfixReleaseImage \e[0m"
          IMG_NAME=$(jq -r ".builds[0].imageName" build.json)
          IMG_WITH_TAG=$(jq -r ".builds[0].tag" build.json)
          IMG_VERSION=$(echo ${IMG_WITH_TAG}  | cut -d ":" -f 2 | cut -d "@" -f 1)
          SVC_NAME=$(echo ${IMG_NAME} | grep -o '[^/]*$')
          echo IMG_NAME="${IMG_NAME}" >> variables
          echo IMG_WITH_TAG="${IMG_WITH_TAG}" >> variables
          echo IMG_VERSION="${IMG_VERSION}" >> variables
          echo -e "\e[95m ${IMG_WITH_TAG}"
          echo SVC_NAME="$(echo "${{ secrets.PAYZAVE_SERVICENAME }}" | sed "s/-db-migration//")" >> variables

      - name: UpdateFlywayJobHotfixReleaseTemplate 
        if: github.ref_type == 'tag' && contains(github.event.head_commit.message, 'hotfix') && github.event.head_commit.message != null && github.event.head_commit.message != ''
        # if: github.event_name == 'push' && contains( github.ref, 'refs/tag' ) && contains(github.event.head_commit.message, 'hotfix')
        run: |
          echo -e "\e[92m START UpdateFlywayJobHotfixReleaseTemplate \e[0m"
          source db/variables
          # git clone https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
          git clone https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
          cd payzave-app-deployment
          git checkout nonprd
          cd overlay/hotfix
          kustomize edit set image ${IMG_NAME}=${IMG_NAME}:${IMG_VERSION}
          cd ../..
          git add -A
          git diff --cached --exit-code --quiet && NOCHG="0" || echo -e "\e[96m Detected Changes"
          if [[ "${NOCHG}" != "0" ]]; then
            git commit -a -m "Update deployment image [${IMG_WITH_TAG}]"
          fi
          ###### Handle Pull & Push Retry ######
          retry=0
          while [ "${retry}" -lt 3 ]
          do
            # git pull https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
            # git push https://${{ secrets.PAYZAVE_GITLAB_USER }}:${{ secrets.PAYZAVE_GITLAB_TOKEN }}@gitlab.com/payzave-gitops/payzave-app-deployment.git
            git pull https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
            git push https://${{ secrets.PAYZAVE_GIT_USER }}:${{ secrets.PAYZAVE_GIT_TOKEN }}@github.com/digital-ventures/payzave-app-deployment.git
            ppResult=$?
            echo -e "\e[31m P&P Result \e[0m : \e[96m $ppResult";
            if [[ "${ppResult}" == "" || "${ppResult}" -eq 0 || -z "${ppResult}" ]]; then
              echo -e "\e[92m Update Deployment success \e[0m"
              break
            else
              retry=$((retry+1))
              if [ "${retry}" -eq 3 ]; then
                echo -e "\e[31m Update Deployment failed, limit exceeded, MANUAL RETRY NEEDED \e[0m"
                exit 1
              else
                echo -e "\e[93m Update Deployment failed, retrying : \e[96m $retry \e[0m"
              fi
            fi
          done
          echo -e "\e[92m ${IMG_NAME}:${IMG_VERSION} \e[0m"
          echo -e "\e[92m FINISH UpdateFlywayJobHotfixReleaseTemplate \e[0m"