on:
  workflow_call:
jobs:
  MavenDeploy:
    # runs-on: ubuntu-latest
    # runs-on: [self-hosted, payzave]
    runs-on: [self-hosted, b2p]
    # container: openjdk:17-jdk-alpine3.14
    container: maven:3.6.3-openjdk-11
    # container: openjdk:18-jdk-alpine3.15
    # container: openjdk:15-jdk-alpine3.12
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.PAYZAVE_GIT_USER }}
          git config --global user.email ${{ secrets.PAYZAVE_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: configNexusCert
        run: |
          openssl s_client -connect ${{ secrets.PAYZAVE_NEXUS_URL }} </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ${{ secrets.PAYZAVE_NEXUS_NAME }}.cert
          keytool -import -noprompt -trustcacerts -alias ${{ secrets.PAYZAVE_NEXUS_NAME }} -file ${{ secrets.PAYZAVE_NEXUS_NAME }}.cert -keystore ${JAVA_HOME}/lib/security/cacerts -storepass ${{ secrets.PAYZAVE_KEYSTORE_PASSWORD }}

      - name: SetupCache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      # - name: SetupMaven
      #   uses: actions/setup-java@v3
      #   with: # running setup-java again overwrites the settings.xml
      #     distribution: 'temurin'
      #     java-version: '11'
      #     server-id: payzave_nexus_release
      #     server-username: MAVEN_USERNAME
      #     server-password: MAVEN_CENTRAL_TOKEN

      - name: SetupMaven
        uses: s4u/maven-settings-action@v2.6.0
        with:
          repositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2/",
                "releases": {
                  "enabled": true
                },
                "snapshots": {
                  "enabled": false
                }
              },
              {
                "id": "payzave_nexus_release",
                "name": "Payzave Release Repository",
                "url": "https://${{ secrets.PAYZAVE_NEXUS_URL }}/repository/maven-releases/",
                "releases": {
                  "enabled": true
                },
                "snapshots": {
                  "enabled": false
                }
              },
              {
                "id": "payzave_nexus_snapshot",
                "name": "Payzave Snapshot Repository",
                "url": "https://${{ secrets.PAYZAVE_NEXUS_URL }}/repository/maven-snapshots/",
                "releases": {
                  "enabled": false
                },
                "snapshots": {
                  "enabled": true
                }
              }
            ]
          pluginRepositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2/",
                "releases": {
                  "enabled": true
                },
                "snapshots": {
                  "enabled": false
                }
              },
              {
                "id": "payzave_nexus_release",
                "name": "Payzave Nexus Repository",
                "url": "https://${{ secrets.PAYZAVE_NEXUS_URL }}/repository/maven-releases/",
                "releases": {
                  "enabled": true
                },
                "snapshots": {
                  "enabled": false
                }
              }
            ]
          servers: |
            [
              {
                "id": "repo.scm",
                "username": "${{ secrets.PAYZAVE_GITLAB_USER }}",
                "password": "${{ secrets.PAYZAVE_GITLAB_TOKEN }}"
              },
              {
                "id": "payzave_nexus_release",
                "username": "${{ secrets.PAYZAVE_NEXUS_USER }}",
                "password": "${{ secrets.PAYZAVE_NEXUS_PASSWORD }}"
              },
              {
                "id": "payzave_nexus_snapshot",
                "username": "${{ secrets.PAYZAVE_NEXUS_USER }}",
                "password": "${{ secrets.PAYZAVE_NEXUS_PASSWORD }}"
              }
            ]

      - name: unitTest
        if: contains( github.ref_name, 'develop' )
        run: mvn -Dmaven.repo.local=.m2 clean test
        # env:
        #   MAVEN_USERNAME: ${{ secrets.PAYZAVE_NEXUS_USER }}
        #   MAVEN_CENTRAL_TOKEN: ${{ secrets.PAYZAVE_NEXUS_PASSWORD }}

      - name: prepareRelease
        if: github.ref_name == 'master' && github.event_name == 'push' && (contains(github.event.head_commit.message, 'maven-release-plugin'))
        run: |
          mvn -B -Dmaven.repo.local=.m2 -DskipTests clean release:prepare

      - name: deployArtifact
        if: contains( github.ref_name, 'develop' ) && github.event_name == 'push' && !(contains(github.event.head_commit.message, ''))
        run: |
          mvn -Dmaven.repo.local=.m2 -DskipTests clean deploy
